org: lzamora2798
app: aws-python-flask-api
service: aws-python-flask-api

frameworkVersion: '3'
useDotenv: true

custom:
  wsgi:
    app: api.app.app

provider:
  name: aws
  runtime: python3.9
  environment:
    WEBSOCKED_URL: ${env:WEBSOCKED_URL}
    CURRENCY_URL: ${env:CURRENCY_URL}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource:
          - "arn:aws:lambda:*"
  cronTask:
    handler: api.crontask.run
    timeout: 600


plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline
